## Create a new recipe

POST http://localhost:8080/recipes
Content-Type: application/json

{
    "name": "Pasta Pomodoro",
    "ingredients": [
        "Tomato sauce",
        "Pasta",
        "Olive oil",
        "Salt",
        "Pepper",
        "Garlic",
        "Onion",
        "Basil",
        "Parmesan cheese"
    ],
    "instructions": "Cook the spaghetti in a large pot of boiling salted water until al dente. Drain well. In a large bowl, whisk together the eggs, cheese, and pepper. While the pasta is still hot, add it to the egg mixture. Add the pancetta and toss well to coat. The heat of the pasta will cook the eggs, but not enough to make them scramble. Serve immediately."
    "cuisine",
    "cuisineId": "2",
    "dietId": "3",
    "difficultyId": "2",
    "image": "/uploads/pasta.avif"
}